version: "3.8"
services:
  app: 
    container_name: four-bros-fe
    image: four-bros-fe
    build: 
      context: .
      target: development
    volumes:
      - ./four-bros-fe:/src
    ports:
      - 3000:3000
